### PR TITLE
cbmc: fix outputs after new release

### PR DESCRIPTION
**Pull request by vmihalko**

### CODE REVIEW

**Comment by vmihalko** [comment]
Outputs is different on fed-34 and fed-35 for `cbmc --bounds-check --pointer-check --memory-leak-check predator/predator-regre-test-0003/test-0003.c --json-ui | cbmc-convert-output`.
It could be because of different glibc version? 
* fed-35: ldd (GNU libc) 2.34
* fed-34: ldd (GNU libc) 2.33

**Comment by kdudka** [comment]
No idea.  Given the fact that the output is technically correct in both the cases, I would just tweak the benchmark to throw away the insignificant details before comparing the actual/expected outputs.

**Comment by vmihalko** [comment]
I'm sorry for making confusion here, but I reply and make commit-correction in https://github.com/aufover/aufover-benchmark/pull/26#issuecomment-1050861776.

Should I put everything into PR:#26 or create a new one for all the `tests/single-c/**/output-diff.sh@${tool}` corrections?

**Comment by kdudka** [comment]
It is up to you.  Thank you for taking care of it!

**Comment by kdudka** [comment]
I believe this is all resolved via #26 so closing.  Thanks!

**Pull request closed without merging**
